### ISSUE TITLE
fail well

### ISSUE THREAD

**Issue by sckott** [agbarnett/helping.funders#2]
to fail well for a nice user experience, maybe validate ORCID ID input?  maybe there's a shiny widget that does that kind of thing already? or just do manually, e.g., right now `0000-0001-6339-03745` gives `Error: 404 - Not found : No entity found for query`  which I understand, but i imagine others won't know what they did wrong (in this case just an extra digit on the end of the ID)

**Comment by agbarnett** [comment]
I've added some basic checks, but I can't get them to appear on the page. The warnings are passed to the orcid function, but don't appear in the output. I can't work out why.

**Comment by sckott** [comment]
hmm, i'm no shiny expert, i'll see if I find anything about displaying Shiny errors

**Comment by agbarnett** [comment]
Fixed now using the "validate" option in shiny
