### ISSUE TITLE
add a license

### ISSUE THREAD

**Issue by jcolomb** [agbarnett/helping.funders#3]
please license the tool, such that we can re-use it.

just push "add a document" button, call it liscence and you will be able to choose one. (MIT is a standard one for code.)

We will then be able to fork and make some modification without liability issue ;)

**Comment by agbarnett** [comment]
Done, I think.

**Comment by jcolomb** [comment]
nope, did you forget to commit?

**Comment by agbarnett** [comment]
Darn. I followed the instructions here https://help.github.com/articles/adding-a-license-to-a-repository/

**Comment by jcolomb** [comment]
it created a new branch, you need to accept the pull request now
